name: Deploy to Vercel

on:
  pull_request:
    branches:
      - development  
      - uat      
      - main     

jobs:
  deploy_development:
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Env Vars on Vercel Project
        uses: dkershner6/vercel-set-env-action@v1
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          projectName: inorbit-web
          envVariableKeys: API_KEY_FIREBASE,AUTH_DOMAIN_FIREBASE,PROJECT_ID_FIREBASE,STORAGE_BUCKET_FIREBASE,MESSAGING_SENDER_ID_FIREBASE,APP_ID_FIREBASE
        env:
          API_KEY_FIREBASE: ${{ secrets.API_KEY_FIREBASE }}
          TARGET_API_KEY_FIREBASE: development
          TYPE_API_KEY_FIREBASE: encrypted
          AUTH_DOMAIN_FIREBASE: ${{ secrets.AUTH_DOMAIN_FIREBASE }}
          TARGET_AUTH_DOMAIN_FIREBASE: development
          TYPE_AUTH_DOMAIN_FIREBASE: encrypted
          PROJECT_ID_FIREBASE: ${{ secrets.PROJECT_ID_FIREBASE }}
          TARGET_PROJECT_ID_FIREBASE: development
          TYPE_PROJECT_ID_FIREBASE: encrypted
          STORAGE_BUCKET_FIREBASE: ${{ secrets.STORAGE_BUCKET_FIREBASE }}
          TARGET_STORAGE_BUCKET_FIREBASE: development
          TYPE_STORAGE_BUCKET_FIREBASE: encrypted
          MESSAGING_SENDER_ID_FIREBASE: ${{ secrets.MESSAGING_SENDER_ID_FIREBASE }}
          TARGET_MESSAGING_SENDER_ID_FIREBASE: development
          TYPE_MESSAGING_SENDER_ID_FIREBASE: encrypted
          APP_ID_FIREBASE: ${{ secrets.APP_ID_FIREBASE }}
          TARGET_APP_ID_FIREBASE: development
          TYPE_APP_ID_FIREBASE: encrypted
      - name: deploy site to vercel (develop)
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--development'
          vercel-org-id: ${{ secrets.DEVELOP_ORG_ID }}
          vercel-project-id: ${{ secrets.DEVELOP_PROJECT_ID }}

  deploy_uat:
    if: github.base_ref == 'uat'  # Verifica se a branch base do PR é 'uat'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Env Vars on Vercel Project
        uses: dkershner6/vercel-set-env-action@v1
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          projectName: inorbit-web
          envVariableKeys: API_KEY_FIREBASE,AUTH_DOMAIN_FIREBASE,PROJECT_ID_FIREBASE,STORAGE_BUCKET_FIREBASE,MESSAGING_SENDER_ID_FIREBASE,APP_ID_FIREBASE
        env:
          API_KEY_FIREBASE: ${{ secrets.API_KEY_FIREBASE }}
          TARGET_API_KEY_FIREBASE: preview
          TYPE_API_KEY_FIREBASE: encrypted
          AUTH_DOMAIN_FIREBASE: ${{ secrets.AUTH_DOMAIN_FIREBASE }}
          TARGET_AUTH_DOMAIN_FIREBASE: preview
          TYPE_AUTH_DOMAIN_FIREBASE: encrypted
          PROJECT_ID_FIREBASE: ${{ secrets.PROJECT_ID_FIREBASE }}
          TARGET_PROJECT_ID_FIREBASE: preview
          TYPE_PROJECT_ID_FIREBASE: encrypted
          STORAGE_BUCKET_FIREBASE: ${{ secrets.STORAGE_BUCKET_FIREBASE }}
          TARGET_STORAGE_BUCKET_FIREBASE: preview
          TYPE_STORAGE_BUCKET_FIREBASE: encrypted
          MESSAGING_SENDER_ID_FIREBASE: ${{ secrets.MESSAGING_SENDER_ID_FIREBASE }}
          TARGET_MESSAGING_SENDER_ID_FIREBASE: preview
          TYPE_MESSAGING_SENDER_ID_FIREBASE: encrypted
          APP_ID_FIREBASE: ${{ secrets.APP_ID_FIREBASE }}
          TARGET_APP_ID_FIREBASE: preview
          TYPE_APP_ID_FIREBASE: encrypted
      - name: deploy site to vercel (UAT)
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--uat'
          vercel-org-id: ${{ secrets.UAT_ORG_ID }}
          vercel-project-id: ${{ secrets.UAT_PROJECT_ID }}

  deploy_production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Env Vars on Vercel Project
        uses: dkershner6/vercel-set-env-action@v1
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          projectName: inorbit-web
          envVariableKeys: API_KEY_FIREBASE,AUTH_DOMAIN_FIREBASE,PROJECT_ID_FIREBASE,STORAGE_BUCKET_FIREBASE,MESSAGING_SENDER_ID_FIREBASE,APP_ID_FIREBASE
        env:
          API_KEY_FIREBASE: ${{ secrets.API_KEY_FIREBASE }}
          TARGET_API_KEY_FIREBASE: production
          TYPE_API_KEY_FIREBASE: encrypted
          AUTH_DOMAIN_FIREBASE: ${{ secrets.AUTH_DOMAIN_FIREBASE }}
          TARGET_AUTH_DOMAIN_FIREBASE: production
          TYPE_AUTH_DOMAIN_FIREBASE: encrypted
          PROJECT_ID_FIREBASE: ${{ secrets.PROJECT_ID_FIREBASE }}
          TARGET_PROJECT_ID_FIREBASE: production
          TYPE_PROJECT_ID_FIREBASE: encrypted
          STORAGE_BUCKET_FIREBASE: ${{ secrets.STORAGE_BUCKET_FIREBASE }}
          TARGET_STORAGE_BUCKET_FIREBASE: production
          TYPE_STORAGE_BUCKET_FIREBASE: encrypted
          MESSAGING_SENDER_ID_FIREBASE: ${{ secrets.MESSAGING_SENDER_ID_FIREBASE }}
          TARGET_MESSAGING_SENDER_ID_FIREBASE: production
          TYPE_MESSAGING_SENDER_ID_FIREBASE: encrypted
          APP_ID_FIREBASE: ${{ secrets.APP_ID_FIREBASE }}
          TARGET_APP_ID_FIREBASE: production
          TYPE_APP_ID_FIREBASE: encrypted
      - name: deploy site to vercel (production)
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.PRODUCTION_ORG_ID }}
          vercel-project-id: ${{ secrets.PRODUCTION_PROJECT_ID }}
